# Generated by Django 2.2.7 on 2019-12-10 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 17, 50, 25, 913351, tzinfo=utc), verbose_name='date published'),
        ),
    ]
