# Generated by Django 2.2.7 on 2019-12-11 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191211_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_series',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_category',
            new_name='series_category',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 15, 27, 1, 744583, tzinfo=utc), verbose_name='date published'),
        ),
    ]
