# Generated by Django 2.2.7 on 2019-12-17 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191217_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='file',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 17, 44, 31, 64522, tzinfo=utc), verbose_name='date published'),
        ),
    ]
