# Generated by Django 2.2.7 on 2019-12-17 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191217_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 18, 45, 59, 161394, tzinfo=utc), verbose_name='date published'),
        ),
    ]
