# Generated by Django 2.2.7 on 2019-12-17 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191217_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_uploader_pk',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 30, 52, 816762, tzinfo=utc), verbose_name='date published'),
        ),
    ]
