# Generated by Django 2.2.7 on 2019-12-17 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191217_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_uploader_pk',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 20, 32, 14, 547452, tzinfo=utc), verbose_name='date published'),
        ),
    ]
