# Generated by Django 2.2.7 on 2019-12-17 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191217_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 21, 4, 38, 131052, tzinfo=utc), verbose_name='date published'),
        ),
    ]
