# Generated by Django 2.2.7 on 2019-12-17 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20191217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 21, 7, 59, 348506, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='video'),
        ),
    ]
