# Generated by Django 2.2.7 on 2020-01-04 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200104_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 13, 23, 41, 360000, tzinfo=utc), verbose_name='date published'),
        ),
    ]
