# Generated by Django 2.2.7 on 2020-01-07 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200107_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.FloatField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 11, 55, 18, 180282, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 11, 55, 18, 176880, tzinfo=utc), verbose_name='date published'),
        ),
    ]
